---
kind: pipeline
type: docker
name: Format check

platform:
  os: linux
  arch: arm64

steps:
  - name: gofmt
    image: golang:alpine
    commands:
      - test -z $(gofmt -l .)

---
kind: pipeline
type: docker
name: Publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Generate new tags
    image: alpine:latest
    commands:
      - echo "latest,latest-$(date +%Y%m%d-%H%M)" > .tags

  - name: Build container
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/globby
      mirror:
        from_secret: DOCKER_MIRROR
      insecure: true
